branch-defaults:
  main:
    environment: hemia-pipe-env
global:
  application_name: Hemia
  default_ec2_keyname: Hemia
  default_platform: 64bit Amazon Linux 2 v3.3.9 running PHP 8.0
  default_region: us-east-1
  profile: eb-cli
  sc: git