branch-defaults:
  main:
    environment: hemia-beanstalk-dev
    group_suffix: null
global:
  application_name: hemia-beanstalk
  branch: null
  default_ec2_keyname: magic-secret-key-goes-here
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application